### ISSUE TITLE
wrong result for region, city and postal region

### ISSUE THREAD

**Issue by Owned67** [Dev-Golem/oneclick-ip#2]
Hello,

`City:
Paris
Region:
Île-de-France
Long/Lat:
48.8763,2.3183
Postal Region:
75366 CEDEX 08`

my ip is ok but all other informations is wrong or it's intented?

**Comment by Dev-Golem** [comment]
Your ip doesn't give you your exact location just general

**Comment by Owned67** [comment]
ok thanks
